project:
  type: website
  output-dir: docs

website:
  title: "RNA-Seq using Nextflow: Day 2"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "nfcore-rnaseq to RStudio"
        menu:
        - text: "RECAP Day 1"
          href: notebooks/1-recap_Day1.html
        - text: Recall the case study
          href: notebooks/recap_casestudy.html  
        - text: "Learning objectives"
          href: notebooks/1.2_Learning_objectives.html
        - text: "Setting up R/RStudio on Pawsey Nimbus"
          href: notebooks/2_nextflow_to_RStudio.html
      - text: "Identifying differentially expressed (DE) genes"
        menu:
        - text: "Exploratory analysis"
          href: notebooks/3.1_exploratory_analysis.html
        - text: "Create the DESeqDataSet object in DeSeq2"
          href: notebooks/4-DE_analysis.html
        - text: "Identify differentially expressed (DE) genes"
          href: notebooks/4-DE_analysis_2.html
      - text: "Enrichment analysis"
        menu:
        - text: "What is enrichment analysis?"
          href: notebooks/6_Whatis_Enrichment_analysis.html
        - text: "DE genes to functional enrichments"
          href: notebooks/7_R_DEGenes_to_functional_enrichments_clusProf.html
          
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




