project:
  type: website
  output-dir: docs

website:
  title: "RNA-Seq using Nextflow: Day 2"
  navbar:
    background: primary
    left:
      - href: https://sydney-informatics-hub.github.io/training.RNAseq.series-quarto/
        text: Home
      - href: https://sydney-informatics-hub.github.io/training.RNAseq.series-quarto/setup.html 
        text: "Setup"
      - text: "Day 2 kick off"
        menu:
        - text: "Recap Day 1"
          href: notebooks/0.0_recap_Day1.html
        - text: "Revisit the case study"
          href: notebooks/0.1_recap_casestudy.html  
        - text: "Learning objectives"
          href: notebooks/0.2_Learning_objectives.html
        - text: "Set up RStudio"
          href: notebooks/0.3_nextflow_to_RStudio.html
      - text: "Gene counts to differentially expressed genes"
        menu:
        - text: "Exploratory analysis"
          href: notebooks/1.0_exploratory_analysis.html
        - text: "Differential expression"
          href: notebooks/1.1_DE_analysis.html
        - text: "Enrichment analysis"
          href: notebooks/1.2_Whatis_Enrichment_analysis.html
      - text: "Day 2 wrap up"
        href: notebooks/2.0_Day2_wrapup.html

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




